services:
  - type: web
    name: arthalens
    runtime: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt && flask db upgrade
    startCommand: gunicorn wsgi:app
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: AI_DB_URL
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: RECAPTCHA_SITE_KEY
        sync: false
      - key: RECAPTCHA_SECRET_KEY
        sync: false
      - key: OWNER_EMAIL
        value: shashwatn2802@gmail.com
